version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - run: lein test
  clojars:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - run: git config --global user.email 'circleci@circleci.com'
      - run: git config --global user.name 'CircleCI'
      - run:
          name: Prepare signing key
          command: |
            echo $GPG_PRIVATE_KEY |base64 --decode |gpg --yes --batch --import
      - run:
          name: Deploy to Clojars
          command: |
            export LEIN_GPG=/home/circleci/jackdaw/.circleci/bin/gpg
            export REAL_GPG=$(which gpg)

            lein do jar, pom, deploy clojars
            
workflows:
  version: 2
  deploy_clojars:
    jobs:
      - clojars:
          context: clojars-deploy
          filters:
            branches:
              only: master
          requires:
            - test
      - test
