version: 2
jobs:
  clojars:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - git config --global user.email 'circleci@circleci.com'
      - git config --global user.name 'CircleCI'
      - lein do deploy, vcs tag --no-sign :prefix 'v', vcs push
  test:
    steps:
      - run: lein test
workflows:
  version: 2
  deploy_clojars:
    jobs:
      - clojars:
           filters:
              branches:
                only: master
           requires:
              - test
      - test
        docker:
        - image: circleci/clojure:lein-2.8.1